
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class stu_update extends javax.swing.JFrame {

    /**
     * Creates new form stu_add
     */
    public stu_update() {
        initComponents();
    }
    public stu_update(String Sesid) {
        initComponents();
        sesid.setText(Sesid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        year = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sbcode = new javax.swing.JTextField();
        cie1 = new javax.swing.JTextField();
        cie2 = new javax.swing.JTextField();
        cie3 = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sesid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("YEAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, 31));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Update Marks");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 240, 64));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_stu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 70, 60));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SUBJECT CODE", "CIE-1", "CIE-2", "CIE-3", "INTERNAL", "EXTERNAL", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 825, 140));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("SEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 70, -1));

        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, 41));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSeparator3.setOpaque(true);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 900, 10));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_button.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, 41));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Subject Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("CIE-2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 50, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("CIE-3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 50, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("EXTERNAL MARKS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("CIE-1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 50, 30));

        sbcode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(sbcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 160, -1));

        cie1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cie1ActionPerformed(evt);
            }
        });
        getContentPane().add(cie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 120, -1));

        cie2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 120, -1));

        cie3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 120, -1));

        em.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 120, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, 41));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stubg1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));
        getContentPane().add(sesid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new stu_update(sesid.getText()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Sid=sesid.getText();
        String Year=(String)year.getSelectedItem();
        String Sem=(String)sem.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
            PreparedStatement psmt=con.prepareStatement("select * from marks where usn='"+Sid+"' and year='"+Year+"' and sem='"+Sem+"'");
            ResultSet rs=psmt.executeQuery();
            ResultSetMetaData rsmd =rs.getMetaData();
            int n=rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=1;i<n;i++)
                {
                    
                    v.add(rs.getString("scode"));
                    v.add(rs.getInt("cie1"));
                    v.add(rs.getInt("cie2"));
                    v.add(rs.getInt("cie3"));
                    v.add(rs.getInt("inter"));
                    v.add(rs.getInt("exter"));
                    v.add(rs.getInt("total"));
                }
                dtm.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int Year1=Integer.parseInt(String.valueOf(year.getSelectedItem()));
        int Sem1=Integer.parseInt(String.valueOf(sem.getSelectedItem()));
         int div=0;
        if(Year1==1 ||  Year1==2 || Year1==3)
            div=800;
        else if(Year1==4 && Sem1==7)
            div=500;
        else if(Year1==4 && Sem1==8)
            div=200;
        sbcode.setEditable(false);
        String Sid=sesid.getText();
         String Sbcode=sbcode.getText();
        int Cie1=Integer.parseInt(cie1.getText());
        int Cie2=Integer.parseInt(cie2.getText());
        int Cie3=Integer.parseInt(cie3.getText());
        int Inter=((Cie1+Cie2+Cie3)/3);
        int Exter=Integer.parseInt(em.getText());
        int Total=Inter+Exter+10;
         if(!(Cie1<31))
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE1 Marks less the 30 ");
                     
                 }
                 else if(!(Cie2<31))
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE2 Marks less the 30 ");
                     
                 }
                 else if(!(Cie3<31))
                     
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE3 Marks less the 30 ");
                     
                 }
                 else if(Exter>60)
                 {
                     JOptionPane.showMessageDialog(null, "Enter the External Marks less the 60 ");
                 }
         else
                 {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
            Statement st=con.createStatement();
            st.executeUpdate("update marks set cie1='"+Cie1+"',cie2='"+Cie2+"',cie3='"+Cie3+"',inter='"+Inter+"',exter='"+Exter+"',total='"+Total+"' where usn='"+Sid+"' and scode='"+Sbcode+"'");
             JOptionPane.showMessageDialog(null, "Successfully Updated");
             setVisible(false);
             new stu_update(Sid).setVisible(true);
        }
        catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, e);
         }
           
             String Year=(String)year.getSelectedItem();
             String Sem=(String)sem.getSelectedItem();
             double Sum1=0.00,Percentage=0.00;  
        try
        {
           
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
            PreparedStatement psmt1=con.prepareStatement("select sum(total) from marks where usn='"+Sid+"' and year='"+Year+"' and sem='"+Sem+"'");
            ResultSet rs1=psmt1.executeQuery();
            if(rs1.next())
            {
                Sum1=rs1.getInt(1);
                Percentage=(Sum1/div)*100;
              
            }
            
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null, e1);
        }
           try
           {
                Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
               String sql="update result set percentage='"+Percentage+"' where usn='"+Sid+"' and year='"+Year+"' and sem='"+Sem+"'";
                  Statement psmt=con.createStatement();
                  psmt.executeUpdate(sql);
                  JOptionPane.showMessageDialog(null, "Updated successfully");
           }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                 }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        
        String Scode=dtm.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String Cie1=dtm.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String Cie2=dtm.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String Cie3=dtm.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String Exter=dtm.getValueAt(jTable1.getSelectedRow(), 5).toString();
        
        sbcode.setText(Scode);
        cie1.setText(Cie1);
        cie2.setText(Cie2);
        cie3.setText(Cie3);
        em.setText(Exter);
        sbcode.setEditable(false);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
      String Sid=sesid.getText();
      String Scode=sbcode.getText();
      String Sem=String.valueOf(sem.getSelectedItem());
       String Year=String.valueOf(year.getSelectedItem());
      int a=JOptionPane.showConfirmDialog(null, "Do you Really want to Delete this sem  Marks","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
            Statement st=con.createStatement();
            st.executeUpdate("delete from marks where usn='"+Sid+"' and sem='"+Sem+"' and year='"+Year+"'");
            setVisible(false);
            new stu_update(sesid.getText()).setVisible(true);
            
        }
        catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, e);
         }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cie1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stu_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cie1;
    private javax.swing.JTextField cie2;
    private javax.swing.JTextField cie3;
    private javax.swing.JTextField em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField sbcode;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JLabel sesid;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
