
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class stu_add extends javax.swing.JFrame {

    /**
     * Creates new form stu_add
     */
    public stu_add() {
        initComponents();
    }
    public stu_add(String Sesid) {
        initComponents();
        sesid.setText(Sesid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        year = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        sbcode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cie1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cie2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cie3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sesid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("YEAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 31));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 900, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Add Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 210, 64));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-stue.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("SEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, 30));

        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, 41));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SAVEBUTTON.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, 41));

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "CIE-1", "CIE-2", "CIE-3", "INTERNAL", "EXTERNAL", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(25);
        jTable2.setRowSelectionAllowed(false);
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 840, 200));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Subject Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, 30));

        sbcode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sbcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbcodeActionPerformed(evt);
            }
        });
        getContentPane().add(sbcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 160, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("CIE-1");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 30));

        cie1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("CIE-2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, 30));

        cie2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("CIE-3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, 30));

        cie3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 110, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("EXTERNAL MARKS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, 30));

        em.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 110, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-small-down.png"))); // NOI18N
        jButton3.setText("Add to Table ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 210, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stubg1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));
        getContentPane().add(sesid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int Year1=Integer.parseInt(String.valueOf(year.getSelectedItem()));
        int Sem1=Integer.parseInt(String.valueOf(sem.getSelectedItem()));
        int div=0;
        if(Year1==1 ||  Year1==2 || Year1==3)
            div=800;
        else if(Year1==4 && Sem1==7)
            div=500;
        else if(Year1==4 && Sem1==8)
            div=200;
        DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel(); 
         if(dtm.getRowCount()==0)
         {
             JOptionPane.showMessageDialog(null, "Table is Empty");
         }
         else if( Year1==1 ||  Year1==2 || Year1==3 && (dtm.getRowCount()<8))
         {
             JOptionPane.showMessageDialog(null, "Please Enter all eight subject Marks");
         }
         else if( Year1==4 && Sem1==8 && (dtm.getRowCount()<2))
         {
             JOptionPane.showMessageDialog(null, "Please Enter all two subject Marks");
         }
           else if( Year1==4 && Sem1==7 && (dtm.getRowCount()<5))
         {
             JOptionPane.showMessageDialog(null, "Please Enter all five subject Marks");
         }
         else
         {
             try
             {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
             String Sid=sesid.getText();
             String Year=(String)year.getSelectedItem();
             String Sem=(String)sem.getSelectedItem();
       
             
             for(int i=0;i<dtm.getRowCount();i++)
             {
                 String Sbcode=dtm.getValueAt(i, 0).toString();    
                 int Cie1=Integer.parseInt(dtm.getValueAt(i, 1).toString());
                 int Cie2=Integer.parseInt(dtm.getValueAt(i, 2).toString());
                 int Cie3=Integer.parseInt(dtm.getValueAt(i, 3).toString());
                 dtm.setValueAt(((Cie1+Cie2+Cie3)/3), i, 4);
                 int Inter=Integer.parseInt(dtm.getValueAt(i, 4).toString());
                 int Exter=Integer.parseInt(dtm.getValueAt(i, 5).toString());
                 dtm.setValueAt(Inter+Exter+10, i, 6);
                 int Tot=Integer.parseInt(dtm.getValueAt(i, 6).toString());
                 String sql="insert into marks values(?,?,?,?,?,?,?,?,?,?)";
                  PreparedStatement psmt=con.prepareStatement(sql);
                  psmt.setString(1, Sid);
                  psmt.setString(2, Year);
                  psmt.setString(3, Sem);
                  psmt.setString(4, Sbcode);
                  psmt.setInt(5, Cie1);
                  psmt.setInt(6, Cie2);
                  psmt.setInt(7, Cie3);
                  psmt.setInt(8, Inter);
                  psmt.setInt(9, Exter);
                  psmt.setInt(10, Tot);
                  psmt.execute();
             }
                JOptionPane.showMessageDialog(null, "Data Added successfully");
                dtm.setRowCount(0);
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null, e);
             }
             String Sid=sesid.getText();
             String Year=(String)year.getSelectedItem();
             String Sem=(String)sem.getSelectedItem();
             double Sum1=0.00,percentage=0.00;  
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
            PreparedStatement psmt1=con.prepareStatement("select sum(total) from marks where usn='"+Sid+"' and year='"+Year+"' and sem='"+Sem+"'");
            ResultSet rs1=psmt1.executeQuery();
            if(rs1.next())
            {
                Sum1=rs1.getInt(1);
                percentage=(Sum1/div)*100;
            }
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null, e1);
        }
           try
           {
                Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
               String sql="insert into result values(?,?,?,?,?) ";
                  PreparedStatement psmt=con.prepareStatement(sql);
                  psmt.setString(1, Sid);
                  psmt.setString(2, Year);
                  psmt.setString(3, Sem);
                  psmt.setDouble(4, percentage);
                  psmt.setString(5,"null");
                  psmt.execute();
                  JOptionPane.showMessageDialog(null, "You can go to makslist and check persentage and result");
           }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
//        DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel();
//
//        String Scode=dtm.getValueAt(jTable2.getSelectedRow(), 0).toString();
//        String Cie1=dtm.getValueAt(jTable2.getSelectedRow(), 1).toString();
//        String Cie2=dtm.getValueAt(jTable2.getSelectedRow(), 2).toString();
//        String Cie3=dtm.getValueAt(jTable2.getSelectedRow(), 3).toString();
//        String Exter=dtm.getValueAt(jTable2.getSelectedRow(), 5).toString();
//
//        sbcode.setText(Scode);
//        cie1.setText(Cie1);
//        cie2.setText(Cie2);
//        cie3.setText(Cie3);
//        em.setText(Exter);
//        sbcode.setEditable(false);

    }//GEN-LAST:event_jTable2MouseClicked

    private void sbcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbcodeActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int Year=Integer.parseInt(String.valueOf(year.getSelectedItem()));
        int Sem=Integer.parseInt(String.valueOf(sem.getSelectedItem()));
        DefaultTableModel dtm=(DefaultTableModel) jTable2.getModel();
        if(sbcode.getText().equals("")||cie1.getText().equals("")||cie2.getText().equals("")||cie3.getText().equals("")||em.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter all the fields ");
        }
        if(Year==4 && Sem==7 && dtm.getRowCount()>4 )
        {
            JOptionPane.showMessageDialog(null, "You can Add only Five Subject Marks for Selected Sem and Year");
        }
        else if(Year==4 && Sem==8 && dtm.getRowCount()>1 )
        {
            JOptionPane.showMessageDialog(null, "You can Add only two Subject Marks for Selected Sem and Year");
        }
        else  if(Year==1 || Year==2 || Year==3  && dtm.getRowCount()>4 )
        {
            JOptionPane.showMessageDialog(null, "You can Add only Five Subject Marks for Selected Sem and Year");
        }
        else
        {
        int i=dtm.getRowCount();
        i++;
        System.out.println(i);
        String Scode=sbcode.getText();
        int Cie1=Integer.parseInt(cie1.getText());
        int Cie2=Integer.parseInt(cie2.getText());
        int Cie3=Integer.parseInt(cie3.getText());
        int Inter =(Cie1+Cie2+Cie3)/3;
        int Exter=Integer.parseInt(em.getText());
        String sas=String.valueOf(Inter);
        String sab=String.valueOf(Inter+Exter+10);
                 if(!(Cie1<31))
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE1 Marks less the 30 ");
                     
                 }
                 else if(!(Cie2<31))
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE2 Marks less the 30 ");
                     
                 }
                 else if(!(Cie3<31))
                     
                 {
                     JOptionPane.showMessageDialog(null, "Enter the CIE3 Marks less the 30 ");
                     
                 }
                 else if(Exter>60)
                 {
                     JOptionPane.showMessageDialog(null, "Enter the External Marks less the 60 ");
                 }
                 else
                 {
                      String data[]={Scode,cie1.getText(),cie2.getText(),cie3.getText(),sas,em.getText(),sab};
            dtm.addRow(data);

                 sbcode.setText("");
                 cie1.setText("");
                 cie2.setText("");
                 cie3.setText("");
                 em.setText("");
                 }
                     
        

     
        } 
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stu_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cie1;
    private javax.swing.JTextField cie2;
    private javax.swing.JTextField cie3;
    private javax.swing.JTextField em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField sbcode;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JLabel sesid;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
