    
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class teach_add extends javax.swing.JFrame {

    /**
     * Creates new form stu_add
     */
    public teach_add() {
        initComponents();
    }
    public teach_add(String userid) {
        initComponents();
        sefid.setText(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        sname = new app.bolivia.swing.JCTextField();
        sid = new app.bolivia.swing.JCTextField();
        spassword = new rojerusan.RSPasswordTextPlaceHolder();
        saddress = new app.bolivia.swing.JCTextField();
        smail = new app.bolivia.swing.JCTextField();
        sphone = new app.bolivia.swing.JCTextField();
        mname = new app.bolivia.swing.JCTextField();
        fname = new app.bolivia.swing.JCTextField();
        sdob = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        sefid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 900, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Add Student");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 210, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T_add__student_big.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 80));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, 41));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("USN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 22));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("STUDENT NAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 183, 162, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("PASSWORD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 245, 131, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("EMAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("PHONE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 357, 145, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("GENDER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("ADDRESS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 414, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jComboBox1.setName(""); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 190, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("DATE OF BIRTH");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("FATHER NAME");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 146, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("MOTHER NAME");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SAVEBUTTON.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, 41));

        sname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sname.setPlaceholder("Enter Student Name");
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 250, -1));

        sid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sid.setPlaceholder("Enter Student Usn");
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 250, -1));

        spassword.setForeground(new java.awt.Color(0, 0, 0));
        spassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        spassword.setPhColor(new java.awt.Color(0, 0, 0));
        spassword.setPlaceholder("Enter Password");
        getContentPane().add(spassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, -1));

        saddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saddress.setPlaceholder("Enter Address");
        getContentPane().add(saddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 250, -1));

        smail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        smail.setPlaceholder("Enter Mail");
        getContentPane().add(smail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, -1));

        sphone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sphone.setPlaceholder("Enter Phone");
        getContentPane().add(sphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 250, -1));

        mname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mname.setPlaceholder("Enter Mother Name");
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 190, -1));

        fname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fname.setPlaceholder("Enter Father Name");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 190, -1));

        sdob.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sdob.setPlaceholder("Enter Date of Birth");
        getContentPane().add(sdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 190, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ORANGEBG.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));
        getContentPane().add(sefid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new teach_add(sid.getText()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

             String Fid=sefid.getText();
         
        String Sid=sid.getText();
        String Sname=sname.getText();
        String Spass=spassword.getText();
        String Smail=smail.getText();
        String Sphone=sphone.getText();
        String Saddress=saddress.getText();
        String Fname=fname.getText();
        String Mname=mname.getText();
        String Sgender=(String)jComboBox1.getSelectedItem();
        String Sdob=sdob.getText();
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pinkbook","root","admin");
              String sql="Insert into student values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement psmt=con.prepareStatement(sql);
            psmt.setString(1,Sid );
            psmt.setString(2, Sname);
            psmt.setString(3, Spass);
            psmt.setString(4, Smail);
            psmt.setString(5, Sphone);
            psmt.setString(6,Saddress );
            psmt.setString(7,Sgender );
            psmt.setString(8,Sdob );
              psmt.setString(9,Fid );
              psmt.setString(10, "Null");
              psmt.executeUpdate();
              
              String sql1="Insert into parents values(?,?,?,?)"; 
              PreparedStatement psmt1=con.prepareStatement(sql1);
              psmt1.setString(1, Sid);
              psmt1.setString(2, Fname);
              psmt1.setString(3, Mname);
              psmt1.setString(4, Sphone);
              psmt1.executeUpdate();
             JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new teach_add().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stu_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teach_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private app.bolivia.swing.JCTextField mname;
    private app.bolivia.swing.JCTextField saddress;
    private app.bolivia.swing.JCTextField sdob;
    public javax.swing.JTextField sefid;
    private app.bolivia.swing.JCTextField sid;
    private app.bolivia.swing.JCTextField smail;
    private app.bolivia.swing.JCTextField sname;
    private rojerusan.RSPasswordTextPlaceHolder spassword;
    private app.bolivia.swing.JCTextField sphone;
    // End of variables declaration//GEN-END:variables
}
